version: '3'

volumes:
  static:
  media:
  letsencrypt:
  production_postgres_data:
  production_postgres_data_backups:

services:
  django:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: django_blog_project_production_django
    working_dir: /app
    volumes:
      - ./blogproject/database/:/app/blogproject/database/
      - ./blogproject/index/:/app/blogproject/index/
      - static:/app/static
      - media:/app/blogproject/media
    env_file:
      - .envs/.production/.django
      - .envs/.production/.postgres
    expose:
      - "8000"
    command: /start.sh

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: django_blog_project_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: redis:5.0

  nginx:
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    image: django_blog_project_production_nginx
    volumes:
      - static:/apps/blogproject/static
      - media:/apps/blogproject/media
      - letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"